// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Para prisma generate, no necesitamos la URL real, solo un placeholder
// Para migrate deploy, se usará la DATABASE_URL del entorno
const getDatabaseUrl = () => {
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }
  // Valor dummy solo para prisma generate (no se conecta realmente)
  return "postgresql://dummy:dummy@localhost:5432/dummy";
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
